global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.CollectionClasses;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using System.Collections.Immutable;
global using CommonSourceGeneratorsHelpers;
global using CommonSourceGeneratorsHelpers.FluentHelpers;